### ISSUE TITLE
No F-Droid release yet

### ISSUE THREAD

**Issue by beerisgood** [wesaphzt/privatelock#1]
Nor the F-Droid client, nor the F-Droid website list your app: https://f-droid.org/packages/com.wesaphzt.privatelock/ which is 15 days on your repository.

Did you know any details?

**Comment by wesaphzt** [comment]
Hi, that link is a placeholder though I'd have expected it to be on there by now.
Unfortunately it's just a waiting game now, waiting for the F-droid bot to pick it up and build it.
I'll post here when it's been done.

**Comment by wesaphzt** [comment]
I've uploaded the apk for you here if you want to try it now but I understand if you'd rather wait.
https://ufile.io/cbc56nhg

**Comment by beerisgood** [comment]
@wesaphzt I think we should open a issue at F-Droid. Still no release yet

**Comment by wesaphzt** [comment]
I've asked for an update, not sure why it's taking so long. Maybe just a shortage of manpower.
You can track the issue at Gitlab here:
https://gitlab.com/fdroid/rfp/issues/1028

**Comment by wesaphzt** [comment]
I can see it's been picked up and built by F-Droid today, so should hopefully be there today or tomorrow.
Closing issue.
