### ISSUE TITLE
Feedback for screen locks

### ISSUE THREAD

**Issue by arukkei** [wesaphzt/privatelock#11]
I find that occasionally the service is triggered at the same time that the screen happens to be solid black.  Realizing this has happened takes a short time.  Could the device vibrate or flash the screen/flashlight just before it locks?  Turning the flashlight on might also help if it has been dropped somewhere dark.

**Comment by wesaphzt** [comment]
Do you mean just before the screen is about to time out and it dims the screen?
Could be a good feature addition for some user feedback/confirmation when it's triggered.

**Comment by wesaphzt** [comment]
Can't imagine flashlight feedback would be very useful or used much if at all, on the off-chance it's dropped in a dark place but I'll look into implementing vibrate feedback.

Non-intrusive user feedback and good for accessibility.

**Comment by wesaphzt** [comment]
https://github.com/wesaphzt/privatelock/commit/248a8eeb0b3b8deabe98cae1c24d457e22f0bbdb
