### ISSUE TITLE
Service restarts itself after closing Private Lock via the Recents menu even if stopped

### ISSUE THREAD

**Issue by ghost** [wesaphzt/privatelock#16]
**Related to:** #13 
**Version:** 1.2 from F-Droid
**Android**: 7.1.1 armv7l
**Video:** [privatelock.zip](https://github.com/wesaphzt/privatelock/files/3681243/privatelock.zip) (GitHub doesn't let me upload `.mp4`)

As you can see in the video, I close Private Lock via the recents menu after pressing the stop button and the ActivityManager schedules a restart of the service. Approximately 14 seconds later, you can see the Private Lock notification reappear. This appears to be a side effect of #13.

**Comment by wesaphzt** [comment]
Thanks for the report, I can replicate it here.

**Comment by wesaphzt** [comment]
I see the issue.
The stop button code is still using the old code, so it crashes and restarts the service - as it's set to be a persistent service upon crash i.e. Android clearing out memory etc. 
Could have sworn I updated it but I guess not, my bad!
Should work fine stopping from notification or widget in the meantime.

**Comment by Nitroretro** [comment]
Thanks! Didn't even realise there was a widget until you've told me, it's really useful :)
-------- Original Message --------

**Comment by ghost** [comment]
Thanks! Didn't even realise there was a widget until you've told me, it's really useful :)

**Comment by wesaphzt** [comment]
Yes, I love the widget! Very convenient to have on the home screen.
