### ISSUE TITLE
bug lock test screen 2:1

### ISSUE THREAD

**Issue by userkilled** [wesaphzt/privatelock#2]
![Screenshot_2019-09-06-23-19-45-838_com wesaphzt privatelock](https://user-images.githubusercontent.com/39238592/64458003-daa39380-d0fc-11e9-9683-d17ce0aa60ab.png)

**Comment by wesaphzt** [comment]
Thank you for submitting.
I'd forgotten about this as it only really affects lower resolution devices.
As the animation is a custom class I'll need to make it responsive rather than a set size.

**Comment by wesaphzt** [comment]
Fixed in https://github.com/wesaphzt/privatelock/commit/87e349d02a949e722878a0f93542611314693f65 for next release.
Closing issue.
