### ISSUE TITLE
[Feature Request] Brute Force protection for fingerprint

### ISSUE THREAD

**Issue by ghost** [wesaphzt/privatelock#20]
Hi and thanks for your greate app! 👍 

After 5 failed fingerprint attempts I found this entries in logcat:

```
android.hardware.biometrics.fingerprint@2.1-service
onError(5)
```

Maybe this is helpful for your and this request 😄

**Comment by wesaphzt** [comment]
Thank you :)
Not quite sure what you're asking for here.
The app only works with PIN entry.

**Comment by ghost** [comment]
Sorry, I didn't write enough context 😆 

It would be nice if this app had brute force protection for the fingerprint sensor. Currently I use the "Tasker"-App to read Logcat entries and reboot the device after 5 tries. Your app forces the password/PIN instead of the fingerprint if someone moves the device too fast. This forcing would also be good for fingerprinting attempts.

**Comment by wesaphzt** [comment]
Hi, I still don't know what you're asking for. It forces the PIN/password due to the way Android works. If it's triggered, the next unlock attempt has to use PIN/password, not fingerprint. This app doesn't have anything to do with the fingerprint unlocking option.
Closing issue.

**Comment by feelingwalnut** [comment]
OP wants this app to watch motion and additionally fingerprint sensor attempts and have either motion or X=number of fingerprint attempts trigger the pin lock screen.
