### ISSUE TITLE
Increase maximum value of the sensitivity slider

### ISSUE THREAD

**Issue by DeerMaximum** [wesaphzt/privatelock#25]
Hey,
it would be possible to increase the maximum value of the sensitivity slider to 60. With the current value (40) too many false triggers occur.

**Comment by beerisgood** [comment]
Confirm. "40" isn't enough if phone get moved to horizontal.

**Comment by wesaphzt** [comment]
Okay no problem, thanks for confirming. I'll increase the max value for the next release.

**Comment by beerisgood** [comment]
Any ETA for the update?

**Comment by Hillside502** [comment]
> Any ETA for the update?

Update?  11 months since the last release.
