### ISSUE TITLE
Lower the notification priority

### ISSUE THREAD

**Issue by Wilker-a** [wesaphzt/privatelock#3]
hi :3

it would be good if there was an option to lower the priority of the notification being shown, as i think that would hide it from the status bar and send it lower in the notifications list (because i think the proccess would be closed if it isn't in foreground). if this option is to be added, that would be great :3 

thank you for reading, and for making this app in the first place \^w\^

**Comment by beerisgood** [comment]
You can minimize the notification by yourself in android.
Just wipe it to right and choice "minimize"

**Comment by wesaphzt** [comment]
Notifications are already set to the lowest importance so it doesn't make sounds and so on (and you're right, there needs to be a notification to start the service). 
When it's been running longer it will naturally move itself down the notification list to be less intrusive.

As @beerisgood mentions, you can adjust the notification settings yourself for individual apps which is the best option to customize it to your needs.
Anyway, glad you like it!

**Comment by Wilker-a** [comment]
in Android 5.1.1 there is not much i can do, unless i block it completely. the problem here is that it stays at the top and also visible at the status bar while it is running... :(

**Comment by beerisgood** [comment]
@Wilker-a you can't ask for a nowadays dev to support such a old system. Or did you use Windows XP on desktop?

You have also a lot more problems  with such old systems then a simple notification. Biggest problem: security

**Comment by Wilker-a** [comment]
i lack the resources to root and update, and i lack the budget for getting a newer system, so i am stuck at an older one.

but i understand what you mean, so thank you anyway \^\^

**Comment by wesaphzt** [comment]
Ah I see, I assumed you were running a more recent version.
I haven't tested it as much on them as the recent Android versions are the target builds.
Looking at it I see I haven't set any notification priority for old builds.
I can set it at the minimum priority which will keep it out of the status bar and push it to the bottom of the list, which makes sense given it's a continuous notification.
It's a minimal effort task, I'll put it in for the next release.

Off topic, security will suffer a bit on older Android versions, in future it's probably a good idea to get a flagship phone that you can load LineageOS on and still receive updates when the manufacturer inevitably abandons it after a year!

**Comment by wesaphzt** [comment]
Changed in commit https://github.com/wesaphzt/privatelock/commit/4d67f4dd47217e9196a49e1a40e2ab50999e7c6f
Low priority rather than minimum to be consistent with later versions behavior so it will still show in the status bar unless there's higher priority notifications.

**Comment by Wilker-a** [comment]
thank you \^-\^
