### ISSUE TITLE
Show actual accelerometer stats on either side of the pie

### ISSUE THREAD

**Issue by zoktiik** [wesaphzt/privatelock#5]
The meter at the bottom used for testing your threshold needs actual numbers. 
A "pie" progress counter, much less one that only moves in a smooth animation, makes the user guess at what exact point the threshold was passed.
The current state of this testing method is ineffective at what it's supposed to do: accurately convey what a sensor is reporting.
Possible stats could include the current accelerometer report, an average over 1-2 seconds, and the last accelerometer report that caused the phone to lock.

**Comment by wesaphzt** [comment]
I did initially display the current accelerator numbers next to it when I was building it, but to be honest I found it useless compared to just looking at it to see when the threshold was passed.
I made it to be a simple, rough, visual guide but I can see some people might find it nice to also have a few stats with it.
I'll look into adding some, perhaps with an option to toggle it on/off.

**Comment by zoktiik** [comment]
The reason for the stats is so you can get a better idea of when the lock will trigger; having this sort of information can help a user know under what specific conditions the lock might trigger from.
The pie would also be more useful if it weren't just a smoothed progress bar, as the smoothing makes it harder to tell what the accelerometer is reporting at a given moment.

**Comment by wesaphzt** [comment]
Average, last and highest stats added https://github.com/wesaphzt/privatelock/commit/0cfce130fd48c5de01bf96ba0e1103c66f7f5833

**Comment by wesaphzt** [comment]
These are post-breach stats which should be adequate.
