### ISSUE TITLE
Annoying notification "Private lock is running"

### ISSUE THREAD

**Issue by giorgiga** [wesaphzt/privatelock#9]
When running without google services (no idea if this also happens with google services) there is a persistent notification "Private lock is running", which I would love to get rid of.

Note that Signal has a similar issue: reference https://github.com/signalapp/Signal-Android/issues/6561

**Comment by wesaphzt** [comment]
It's not ideal but a notification is required to run the background service in Android (for a while now).
It's the reason why a lot of old apps don't work anymore (such as PluckLockEx), they haven't been updated to make the necessary changes.
The best option is probably to play around with the notification options in Android, though it might also kill the service if you turn off notifications entirely for the app.
Swiping the notification left will bring up some settings you can change.
